language: php

branches:
  # Only test the main branch and SemVer tags.
  only:
    - main
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

php:
  - 7.0
  - 5.6
  - 5.5

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - vendor/bin/phpcs --standard=PSR2 -n src
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
